name: "Build openssl interop container from master"

on:  
  workflow_dispatch:

jobs:
  update_quay_container:
    runs-on: ubuntu-22.04-ppc64le
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: "log in to quay.io"
        run: |
          docker login -u rahulssv -p ${{ secrets.QUAY_IO_PASSWORD }} quay.io
      - name: "Build container"
        run: |
          cd test/quic-openssl-docker/
          docker build -t quay.io/rahulssv/openssl-quic-interop:latest .
      - name: "Push to quay"
        run: |
          docker push quay.io/rahulssv/openssl-quic-interop:latest

